### ISSUE TITLE
A Profile Page

### ISSUE THREAD

**Issue by ty-everett** [p2ppsr/ninja-ui#2]
On the left menu, there should be a new page added called "Profile"

On the page it should display my current name, photo URL (just the URL is fine for now, no need to render the image yet, because it needs [UHRP React](https://github.com/p2ppsr/uhrp-react)), and my current Paymail handle.

I should be able to view my name, photo URL and Paymail, and I should be able to use an edit mode to change them.

**Comment by ericx2x** [comment]
I'm just doing the front end for this but you will hook the data up to a backend at some point?

**Comment by ty-everett** [comment]
The frontend should hook into `ninja.getAvatar`, `ninja.setAvatar`, `ninja.getPaymail`, and `ninja.setPaymail`.

For the getters, just call the functions when the page loads to show the data on the screen.

For the setters, just call them with whatever is in the edit-mode text fields whenever the user hits "save".

**Comment by ty-everett** [comment]
Don't worry about rendering an `<img>` tag, and **definitely** don't worry about file upload. Literally just have the user enter a "photo URL" in the text field for `setAvatar`. That is fine.
