### ISSUE TITLE
A way to use getTransactionWithOutputs

### ISSUE THREAD

**Issue by ty-everett** [p2ppsr/ninja-ui#3]
On the left menu there should be a new [+] New Transaction button, and it should open a little modal. The modal should allow the person to interact with the getTransactionWithOutputs function. There should be text fields for each of the parameters of the functions, and there should be a way to add and remove outputs from the array. Each output should have two text fields, one for pasting in the script hex and another to specify the amount of satoshis.

**Comment by ericx2x** [comment]
What is the getTransactonWithOutputs function? I don't see that string in the DOJO api or in the ninja-ui repo.

**Comment by ty-everett** [comment]
@ericx2x you should not refer to the Dojo docs as the primary reference point, but should look at [UTXONinja docs](https://github.com/p2ppsr/utxoninja) first. Dojo docs are a good fallback resource in case something isn't clear from looking at the README.md file of UTXONinja.

Most of the needed UI work here is going to be based on what is in the UTXONinja readme
